### ISSUE TITLE
media upload happens without me saving

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#347] opened 2021-05-18 15:07 UTC
i wanted to look at the media upload interface on dev-app, so clicked on the "New" button - but instead of getting the upload interface, i got a window to browse & select a file from my computer. i had to do this in order to see the interface; but i didn't want to upload the file that i'd selected, so after looking at the interface, i then clicked the X in the corner to close it without saving it. however, the message came up that my media item had been saved (even though i hadn't pressed save) and i can now see it there in the media list.
this workflow is likely to lead to a lot of unintentional uploads!

**Comment by nguyenhongphat0** [comment] 2021-05-18 15:13
Yes I forgot to prompt you that, since I don't want to have different form on create and edit media, I changed the upload flow. Here is now media got created:
- When you click the new button, a choose file dialog will appear so that you can choose a file
- A media will be uploaded after that, and media type will be determined based on the extension (for example avatar for .png,.gif,...)
- The same form as media edit will appear, allow you to customise the name, type, voice, multi frames and assign to stages stuff

Since we have media deletion feature at the moment, unintentional uploads can be avoided. Maybe I can automatically delete the media if you click the `X` button without saving?

**Comment by helenvarley** [comment] 2021-05-18 15:41
i think the idea of the flow is fine - it makes sense that you first navigate to the file, and it's great if the type can be auto-detected (as long as you can change it, because it won't know which type an image file should be).
but it should not actually upload the file until you hit save. sure, we can delete it after, but probably a lot of people won't do that, so there will be unnecessary media uploaded. 
it also means we can't demonstrate the process easily - we we do often in workshops - without actually uploading something. you can't see the upload interface unless you have selected a file.

**Comment by nguyenhongphat0** [comment] 2021-05-18 15:51
Yes make sense 🙌 So the flow will be kept but media won't actually upload until you hit the Save button 👌

**Comment by vickis** [comment] 2021-05-18 19:09
That makes more sense yes

**Comment by helenvarley** [comment] 2021-05-19 15:07
i tested it, & the new layout is great! (altho the image preview could be smaller) BUT when i clicked on the multiframe toggle, it saved the media upload & threw me back to the media list.
so i could not make a multiframe av in that step, & i could not decide that i didn't want to upload it and cancel out of the process.
but i did assign it to my stage & give it a voice :)

**Comment by helenvarley** [comment] 2021-05-19 15:09
and it seems that assigning the red car in the upload process has unassigned the other avatar that was already assigned to my stage ... :/

**Comment by nguyenhongphat0** [comment] 2021-05-19 15:13
> and it seems that assigning the red car in the upload process has unassigned the other avatar that was already assigned to my stage ... :/

No way 🤐 (your skategrrl still there)

<img width="1330" alt="Screenshot 2021-05-19 at 22 12 21" src="https://user-images.githubusercontent.com/29925961/118837708-4b014100-b8ef-11eb-82fe-415413ec1f02.png">

**Comment by helenvarley** [comment] 2021-05-19 16:03
i put her back on, to test the stage updated message! :laughing:

**Comment by nguyenhongphat0** [comment] 2021-05-20 14:45
It should works now:

https://user-images.githubusercontent.com/29925961/118999610-9df0fc00-b9b4-11eb-8642-e07f9b944fc8.mov

> and it seems that assigning the red car in the upload process has unassigned the other avatar that was already assigned to my stage ... :/

And about this, maybe your stage's media got swept before that (I don't know if I'm the causer 😅), I uploaded and assigned a lot of media, the other assigned media stay untouched 🤔

**Comment by helenvarley** [comment] 2021-05-20 15:19
great - it seems to work now, and i was able to cancel out from the media upload without accidentally uploading a file. 

can we improve the layout of the media upload interface? there is a huge amount of space given to the image, and i have to move the cursor quite a lot to reach things. could the media be on one side of the screen for example, and the tabs/buttons/fields be on the other side as a list? (should i make a new issue for this? and add @elisadcg ?)

**Comment by nguyenhongphat0** [comment] 2021-05-20 15:26
Media on the left and fields on the right is what it used to be 🤣 But sure, let me know how we can improve this layout

**Comment by helenvarley** [comment] 2021-05-20 15:55
let's talk with @elisadcg  for some ideas :)

**Comment by elisadcg** [comment] 2021-05-21 07:23
If we decrease the black space we get this dialog smaller.
![issue347](https://user-images.githubusercontent.com/7611913/119098033-b2191580-ba15-11eb-8a31-68c2c6142bfc.png)
If the window is smaller, then the parts can go under
![issue347-b](https://user-images.githubusercontent.com/7611913/119098324-fe645580-ba15-11eb-8910-d2da87ff072e.png)

But i did not understand the multiframe tab.... we are in the media page. This dialog open when we edit an already media uploaded. For what purpose the artist need the multiframe tab ?

**Comment by helenvarley** [comment] 2021-05-21 10:28
we want this layout for both the media upload, and the media edit interface. it looks great to me - much more compact and easier to move the cursor around.
we do need the multiframe tools; i want to be able to, in the upload process, upload several frames at one time (as we could in the old UpStage) - so it needs to be a button to add another file. in the edit media we need something like what is there now, that you can select additional media from what has already been uploaded.
can there be tabs for voice, stage and multiframe? (like in the current version) & in the multiframe tab there is the option to upload more files or select from already uploaded media?
(should i make a new issue for this?)

**Comment by nguyenhongphat0** [comment] 2021-05-21 13:01
Yes please put it in a new issue or append to this issue instead: https://github.com/upstage-org/mobilise/issues/35
This issue should be closed now!

**Closed by nguyenhongphat0** 2021-05-21 13:01 UTC
Labels: backstage, media management
