### ISSUE TITLE
audio: sometimes files do not play

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#434] opened 2021-06-22 20:46 UTC
there is an issue with some files sometimes not playing, but it is unfortunately difficult to replicate. i click on the track, and the first second is heard then it stops. i noticed this a couple of times in previous days but could not replicate it, then this evening it happened again & was also the same for others.

i thought it might have been to do with the file format as one of them i could see was an ogg file. however now it is working ... :thinking: 

so i'm just making this issue as something to look out for.

**Comment by elisadcg** [comment] 2021-06-25 13:49
Is it not related to the browser which doesn't allow some file format for sound ?
https://caniuse.com/?search=ogg

**Comment by vickis** [comment] 2021-06-25 20:15
This happened for all of us at the same time
I think Eva uploaded s  m e more files and we all had to reload before they
played ...
seemed more universal than browser specific - will be another chance to
test tonight :)

**Comment by helenvarley** [comment] 2021-06-25 21:46
it also came right later, so i don't think it can be the file format - because that hadn't changed. i noticed this bug earlier but wasn't sure if it was only me so hadn't logged it yet.

**Comment by nguyenhongphat0** [comment] 2021-07-18 05:46
This is not an issue with file format, I can confirm.
This can be an impact on other features, or maybe just caching issue. I cannot reproduce this, hope it was fixed when I did a refactor of audio tool as part of #472 
I will close this issue for now, feel free to re-open this if the bug is still happening. Thank you 🙏

**Closed by nguyenhongphat0** 2021-07-18 05:46 UTC
Labels: audio
