### ISSUE TITLE
player delete error

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#266] opened 2021-04-13 09:45 UTC
Anita (username anitah) has logged in, created a stage (https://app1.upstage.org.nz/V4.0/ui/live/xy) and assigned media to it, but when she is on the stage she cannot do anything on the stage, and we cannot see her. she can't see us, or what we are doing on the stage, she doesn't see the backdrop or media or chat. it's like a parallel universe ... !!
we tried to delete her account, so that she could recreate it, but when we did this there came an error message, and vicki got the message that karla had been deleted. it then showed that both anita and karla (whose account appears next to anita's in the list) had been deactivated - but not deleted. anita was still logged in and able to do things. we reactivated the accounts, and then vicki tried again to delete anita, but it still didn't work.
here are my screenshots:
![Screenshot at 2021-04-13 11-24-31](https://user-images.githubusercontent.com/3437324/114532894-94ee6b80-9c4d-11eb-88d7-bc1ae0290e77.png)
![Screenshot at 2021-04-13 11-23-46](https://user-images.githubusercontent.com/3437324/114532896-95870200-9c4d-11eb-9d39-83f25fa381e4.png)

**Comment by helenvarley** [comment] 2021-04-13 09:46
@vickis did you also take screenshots?

note: anita will need to be able to access UpStage on friday for our workshop in graz; maybe a workaround for now is for someone to delete her account from the database and she creates a new account?

**Comment by vickis** [comment] 2021-04-13 09:49
i had the same screen shot
the error message was when deleting
 the deactivation and reactivation appeared to work well

**Comment by nguyenhongphat0** [comment] 2021-04-13 14:12
When you delete a user, what happen to these stages created by that user? Should I delete it as well @helenvarley 🤔

**Comment by nguyenhongphat0** [comment] 2021-04-13 14:17
> but when she is on the stage she cannot do anything on the stage, and we cannot see her. she can't see us, or what we are doing on the stage, she doesn't see the backdrop or media or chat. it's like a parallel universe

I believe this is not an issue with her account, so delete it and recreate won't help. I assume Anita was using Firefox. This is the problem with Firefox after we switch to https: 
<img width="1081" alt="Screenshot 2021-04-13 at 21 16 27" src="https://user-images.githubusercontent.com/29925961/114567518-83cd4b00-9c9d-11eb-80f2-bcc353ba6e70.png">

**Comment by paul-rohrlach** [comment] 2021-04-13 14:19
> When you delete a user, what happen to these stages created by that user? Should I delete it as well @helenvarley 🤔

I would say yes.  A warning should be given to the admin deleting the user that this will happen,  they can then choose whether they want to go and reassign the stages, etc. or whether they want to continue with the deletion.

**Comment by vickis** [comment] 2021-04-13 18:23
Yes an additional problem may have been caused by us being on the stage
also
We had told jasper not to use Firefox but I am not sure if Anita was
continuing to use it - agree there should be a warning about associated
media or stages

**Comment by nguyenhongphat0** [comment] 2021-04-13 18:46
We can now delete Anita. About the issue with Firefox I think it should go in #252

**Closed** 2021-04-16 06:48 UTC
Labels: bug, fixed
