### ISSUE TITLE
speech bubbles for thinking and shouting

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#355] opened 2021-05-19 13:59 UTC
previously in UpStage we had three different kinds of speech bubbles: 
- normal
- thinking: triggered by typing a : at the start of the avatar's text. it meant that the text was silent, not voiced, appeared as blue text in the chat window, and the speech bubble was a fluffy thought cloud.
- shouting: triggered by typing a ! at the start of the avatar's text. it meant that the text was spoken a bit louder than normal, appeared as red capitalised text in the chat window, and the speech bubble was a jagged red shape with capitalised text.

it would be great to have something similar :)

![speech_helen](https://user-images.githubusercontent.com/3437324/98269302-d89dc480-1f8d-11eb-93ed-7d18ff50da33.jpg)

![think_vicki](https://user-images.githubusercontent.com/3437324/98269198-c459c780-1f8d-11eb-8309-c5abf56685aa.jpg)

![shouting_dan](https://user-images.githubusercontent.com/3437324/98269140-b146f780-1f8d-11eb-863e-d151468ec20e.jpg)

**Comment by nguyenhongphat0** [comment] 2021-05-19 15:06
Yes these different shape of speech bubbles can be achieved in our new UpStage 👌 It's just matter of time and priority 🤣

**Comment by helenvarley** [comment] 2021-06-09 10:26
seeing you are working on this now, @nguyenhongphat0 - we had a comment from someone in the workshop today (karla, who was one of the original creators of the first UpStage) about the way that the speech bubbles appear & disappear. she found the bounciness a bit distracting, that it took too much attention to the speech bubble.
i had been thinking that it could be good to have options for speech bubble appearance - in the old UpStage they appeared and then faded out slowly, & this was quite good.
could it be that in the stage management, we can choose what type of speech bubble animation we want?

**Comment by vickis** [comment] 2021-06-09 10:32
agree choosing animation would be great
fade is good - but sometimes the freshness of the alert might be what is
required :)

**Comment by helenvarley** [comment] 2021-06-17 12:36
we had fun yesterday playing with the new speech bubbles :) but they need a bit of tweaking:
- in the normal speech bubble, there is often a lot of empty space around the text - the bubble is too big; but also the last line is often falling out the bottom.
- the font size of the thought bubble is too small.
sorry i forgot to take screengrabs.

**Comment by vickis** [comment] 2021-06-17 18:32
agree - could the text be 'always at the top'

**Comment by helenvarley** [comment] 2021-06-21 13:35
any chance the speech bubbles & chat styling can be on app1 for tomorrow??

**Comment by nguyenhongphat0** [comment] 2021-06-21 14:20
I rolled AP-5 to app1 (which means app1 and dev-app1 should have all the latest features). Hope Paul will be okay with this because we must wait until AP-5 got merged into main to roll to app1 (which will be this weekend) 😅

**Comment by paul-rohrlach** [comment] 2021-06-21 14:27
I don't mind.

If it breaks, _you_ fix it 😆

**Comment by helenvarley** [comment] 2021-06-21 14:32
thank you!

**Comment by nguyenhongphat0** [comment] 2021-06-23 06:12
I believe we can close this issue now:
- Thought font size is not too small anymore
- Speech bubbles is now more fit to the text inside it

**Comment by helenvarley** [comment] 2021-06-23 10:25
not quite, sorry ...
![Screenshot at 2021-06-23 12-24-32](https://user-images.githubusercontent.com/3437324/123081313-1fa5d080-d41e-11eb-9b29-e68b45a0ab4f.png)

**Comment by nguyenhongphat0** [comment] 2021-06-23 15:31
I made some improvements, but couldn't test on all size. This is an annoying issue and I will made improvements on it times by times. We will close this issue when there is no weird bubble size anymore 👌

**Comment by vickis** [comment] 2021-06-23 18:26
It seems sometimes the issue is where the avatar is near the edges of the
stage
CanUpStae detect position and shift the bubble away from the edge?
Eg if avatar is in top corner bubble might come out below or to the side
(into the stage ...

: some sort of speech spatial awareness

**Comment by elisadcg** [comment] 2021-06-25 13:41
if avatar is on the top and make it speech, tue bubble appear tronkated
![Uploading Screenshot_20210624_212956.png…]()

**Comment by helenvarley** [comment] 2021-06-25 21:53
yes the speech bubble needs to be able to flip to underneath if it's going to get lost at the top

**Comment by nguyenhongphat0** [comment] 2021-06-26 04:33
Got this! And seeing 12 players and 17 audiences in your stage make me so excited @elisadcg 🤩

**Comment by helenvarley** [comment] 2021-06-26 09:37
i think we had around 30+ on thursday - is there a way yet that we record these stats?

**Comment by nguyenhongphat0** [comment] 2021-06-27 05:39
We already have these stats recorded, it is part of the event archive. What we need is some way to visualise that stats, might be a line chart to show numbers of players/audiences by time 🤔

**Comment by helenvarley** [comment] 2021-06-28 17:17
it would be good to be able to find the recording, chat log and statistics for a performance all together ... somehow? like a report view?

**Comment by nguyenhongphat0** [comment] 2021-06-29 06:10
Speech bubble now have it position changed it if hit the walls 👌 
<img width="1302" alt="Screenshot 2021-06-29 at 13 07 56" src="https://user-images.githubusercontent.com/29925961/123746048-4d39c080-d8db-11eb-89c1-8ff96719aa77.png">

**Comment by vickis** [comment] 2021-06-29 08:12
Super!! :)

**Comment by helenvarley** [comment] 2021-07-01 14:56
reopening this in case it is possible to improve the movement: if i move my avatar when its speech bubble is there, the speech bubble jumps immediately to the new place, and the avatar follows. this must look quite weird to the audience, because they don't know that the avatar is going to arrive at that point.
is it possible for the speech bubble to move WITH the avatar?

also, the text is still not fitting that well in the shouting and thought bubbles ...
![Screenshot at 2021-07-01 16-55-25](https://user-images.githubusercontent.com/3437324/124145669-481c7300-da8d-11eb-9a4b-f36ee43c21a4.png)
![Screenshot at 2021-07-01 16-55-05](https://user-images.githubusercontent.com/3437324/124145673-494da000-da8d-11eb-87ce-94776fd017e5.png)

**Comment by nguyenhongphat0** [comment] 2021-07-02 08:00
> also, the text is still not fitting that well in the shouting and thought bubbles ...

Another improvement 👌 
<img width="285" alt="Screenshot 2021-07-02 at 14 58 20" src="https://user-images.githubusercontent.com/29925961/124241476-fbe13980-db45-11eb-82ac-b438eb8f6785.png">
<img width="285" alt="Screenshot 2021-07-02 at 14 58 25" src="https://user-images.githubusercontent.com/29925961/124241487-fd126680-db45-11eb-87be-07fdb79d1bb7.png">

> is it possible for the speech bubble to move WITH the avatar?

In that case the speech bubble will ROTATE with the avatar, we already open an issue about that because we need the bubble straight no matter how the avatar is rotated 🤔

**Comment by helenvarley** [comment] 2021-07-05 14:40
hmm yes, we don't want the speech bubble to rotate ... :thinking:

**Comment by helenvarley** [comment] 2021-07-05 14:45
![Screenshot at 2021-07-05 16-44-10](https://user-images.githubusercontent.com/3437324/124488628-5a115500-ddb0-11eb-99b4-d3aad5f33192.png)

**Comment by helenvarley** [comment] 2021-07-11 02:08
it's fitting better now, sometimes there is more space than necessary - but it's better to have too much space than not enough!
one other thing: bubbles with very few words are displayed with a much shorter "stalk", closer to the avatar. it would be better for them all to have the same distance from the avatar.
![Screenshot at 2021-07-11 14-03-47](https://user-images.githubusercontent.com/3437324/125180710-6fbfc800-e251-11eb-92c8-80a7ed9feb9f.png)
![Screenshot at 2021-07-11 14-03-54](https://user-images.githubusercontent.com/3437324/125180711-70f0f500-e251-11eb-92fe-ab7e57f6c225.png)
![Screenshot at 2021-07-11 14-02-38](https://user-images.githubusercontent.com/3437324/125180714-71898b80-e251-11eb-8351-a3f5d9cbf0fb.png)

**Comment by nguyenhongphat0** [comment] 2021-07-12 03:34
More enhancements coming your way 😆 
<img width="193" alt="Screenshot 2021-07-12 at 10 27 05" src="https://user-images.githubusercontent.com/29925961/125226680-b7029300-e2fb-11eb-8674-f25d3f8400e7.png">
<img width="185" alt="Screenshot 2021-07-12 at 10 27 44" src="https://user-images.githubusercontent.com/29925961/125226730-ceda1700-e2fb-11eb-8f26-e5e85898d7e1.png">
<img width="201" alt="Screenshot 2021-07-12 at 10 28 18" src="https://user-images.githubusercontent.com/29925961/125226763-e2857d80-e2fb-11eb-8789-992bc55819c9.png">

**Comment by vickis** [comment] 2021-07-12 03:57
awesome Phat!

**Comment by helenvarley** [comment] 2021-07-19 03:26
looks great :)
could they fade away a little slower?

**Comment by nguyenhongphat0** [comment] 2021-07-19 13:39
You can choose how slow or how fast the bubble and curtain animation in the Customisation section 👍 
<img width="1001" alt="Screenshot 2021-07-19 at 20 38 52" src="https://user-images.githubusercontent.com/29925961/126168726-c5259de6-3fbf-4c56-a28a-dbf4e34d50f9.png">

**Comment by vickis** [comment] 2021-07-19 14:58
great!

**Comment by helenvarley** [comment] 2021-07-19 23:15
ahah, of course :)

**Comment by nguyenhongphat0** [comment] 2021-07-21 14:10
Look like this issue is (finally) resolved 🤣

**Closed by nguyenhongphat0** 2021-07-21 14:10 UTC
Labels: avatars, chat
