### ISSUE TITLE
weird voice thing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#400] opened 2021-06-09 10:23 UTC
today in our workshop i did not hear any avatar voices; after we finished i went back in & tried the dave avatar, no voice. then i opened the context menu, changed the voice, & clicked on the button to test it. this triggered a cacophony of voices - i guess all the voices that we had not heard during the workshop.
maybe this is just a temporary bug, or maybe it was only me, but i have the feeling that nobody heard any voices  during the workshop. @vickis did you?

**Comment by vickis** [comment] 2021-06-09 10:30
no initially none but changed the voice and then heard them

**Comment by helenvarley** [comment] 2021-06-09 10:44
so that means that clicking to enter the stage doesn't work to activate the voices?

**Comment by nguyenhongphat0** [comment] 2021-06-09 13:35
Now that sounds creepy 🥶

**Comment by nguyenhongphat0** [comment] 2021-06-16 07:29
I tried many times, still cannot reproduce this bug 😫 Maybe it was some caching issue 🤔 I will close this issue for now, we can re-open it any time if the issue still happening!

**Closed by nguyenhongphat0** 2021-06-16 07:29 UTC
Labels: avatars

**Comment by helenvarley** [comment] 2021-06-16 12:24
we were rehearsing this morning & i learned some things: 
- if you have not saved an avatar voice backstage, the avatar will have no voice at all until you open the voice settings and click save (even without adjusting what is there)
- there are still some times when for unknown reasons, one or more of us did not hear an avatar's voice. i noticed this happened a couple of times with the avatar i was using - the voice was working, then one line of text was not spoken, then it worked again. this also used to happen in the old UpStage.
- one time when i re-entered the stage, i did not hear any avatar voices until i opened the voice settings of the avatar i was holding and clicked save; then i heard all the voices. maybe this happens if you are holding an avatar that hasn't got a saved voice? but you should hear the other voices even if you are not holding anything ...

it really has to be tested with multiple players on the stage, because if you're alone there are no others operating avatars for you to hear or not ...
